### ISSUE TITLE
Should ios-safari check include Facebook browser?

### ISSUE THREAD

**Issue by golmansax** [braintree/browser-detection#26]
Hi, one of our customers used Facebook browser on iOS and they complained that the Venmo integration did not work properly (opened up a new tab).  My guess is that it's because `isIosSafari()` is returning true for the below user agent.

```
Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 LightSpeed [FBAN/MessengerLiteForiOS;FBAV/304.0.0.36.119;FBBV/277977129;FBDV/iPhone10,4;FBMD/iPhone;FBSN/iOS;FBSV/14.4.1;FBSS/2;FBCR/;FBID/phone;FBLC/en;FBOP/0]
```

Thoughts on how this should be handled?  Thanks.

**Comment by crookedneighbor** [comment]
This is because Facebook is changing the useragent of their webview. If you'd like to open a PR to account for Facebook (it's a big enough app that I think it would be fine to have special handling for it) to make it return `false` for `isIosSafari` and `true` for `isIosWebview`, then I'd be happy to review it.

**Comment by crookedneighbor** [comment]
Added the `v2` label to this so we can tackle this as part of a major version bump for the library. Our tentative plan is to add a `check` that the useragent includes `Safari` which should exclude many of these in-app browsers. 

However, since right now the check for isIosSafari is inclusive of ios webviews, we can't make that update without a breaking change. (in fact, the Venmo component in the Braintree SDK is reliant on this behavior right now)

Once we're ready to do a major version bump on the Braintree SDK, we can make a major version bump here and be more accurate about how `isIosSafari` returns.

**Comment by golmansax** [comment]
@crookedneighbor Finally set up a PR to fix this issue.  Thanks for describing what needed to happen!
